#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


INTERFACE="${BLOCK_INSTANCE:-enp3s0}"

state="$(cat /sys/class/net/$INTERFACE/operstate)"
myssid=$(nmcli -t -f NAME connection show --active)

if [ "$state" != "up" ]; then
	echo ""
	echo ""
	echo "#FF0000"
	exit 0
fi


ipaddr="$(ip addr show $INTERFACE | perl -n -e'/inet (.+)\// && print $1')"
ipaddr="${ipaddr:-0.0.0.0}"

# full text
# spd="$(echo `~/.config/i3blocks/speed.sh`)"
echo -n "$myssid $ipaddr"
[ -n "$speed" ] && echo " ($speed Mbits/s)" || echo

# short text
echo "$ipaddr"
